In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math

## 1. Viết hàm tính các chuẩn p = 1, 2, inf cho 50 dòng đầu tiên của array.

In [11]:
df = pd.read_csv('/content/ionosphere.data', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g


In [12]:
df.pop(df.columns[-1])
df

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,0.56811,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.20332,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,0.57528,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,1.00000,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,0.03286,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,0.95378,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.94520,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.93988,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,0.91050,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243


In [13]:
# array
array = df.values
print(array)

point1 = array[0, :]
point2 = array[1, :]
point3 = array[2, :]
# p=1
dist01_2 = np.linalg.norm(point1 - point2, 1)
dist01_3 = np.linalg.norm(point1 - point3, 1)
# p=2
dist1_2 = np.linalg.norm(point1 - point2)
dist1_3 = np.linalg.norm(point1 - point3)
# p=inf
dist11_2 = np.linalg.norm(point1 - point2, np.inf)
dist11_3 = np.linalg.norm(point1 - point3, np.inf)
# print results
print(dist1_2)
print(dist1_3)
print(dist01_2)
print(dist01_3)
print(dist11_2)
print(dist11_3)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
2.7763589251571923
1.1697276018372824
13.080950000000001
5.359709999999999
1.12221
0.45772


In [14]:
def compute_distance_matrices(array, num_rows=50):
    # Lấy 50 dòng đầu tiên
    data = array[:num_rows, :]
    n = data.shape[0]

    # Tạo ma trận khoảng cách
    dist_matrix_p1 = np.zeros((n, n))  # p = 1 (Manhattan)
    dist_matrix_p2 = np.zeros((n, n))  # p = 2 (Euclidean)
    dist_matrix_pinf = np.zeros((n, n))  # p = inf (Chebyshev)

    # Tính khoảng cách giữa tất cả các cặp điểm
    for i in range(n):
        for j in range(i + 1, n):
            # Tạo 2 điểm
            point1 = data[i, :]
            point2 = data[j, :]

            # p=1
            dist_p1 = np.linalg.norm(point1 - point2, 1)
            dist_matrix_p1[i, j] = dist_p1
            dist_matrix_p1[j, i] = dist_p1

            # p=2
            dist_p2 = np.linalg.norm(point1 - point2, 2)
            dist_matrix_p2[i, j] = dist_p2
            dist_matrix_p2[j, i] = dist_p2

            # p=inf
            dist_pinf = np.linalg.norm(point1 - point2, np.inf)
            dist_matrix_pinf[i, j] = dist_pinf
            dist_matrix_pinf[j, i] = dist_pinf

    # Tạo nhãn ma trận
    labels = [f"p{i+1}" for i in range(n)]

    # Print results
    print("\nManhattan, p=1:")
    df_dist_p1 = pd.DataFrame(dist_matrix_p1, index=labels, columns=labels)
    print(df_dist_p1.round(4))

    print("\nEuclidean, p=2:")
    df_dist_p2 = pd.DataFrame(dist_matrix_p2, index=labels, columns=labels)
    print(df_dist_p2.round(4))

    print("\nChebyshev, p=inf:")
    df_dist_pinf = pd.DataFrame(dist_matrix_pinf, index=labels, columns=labels)
    print(df_dist_pinf.round(4))

compute_distance_matrices(array, num_rows=50)


Manhattan, p=1:
          p1       p2       p3       p4       p5       p6       p7       p8  \
p1    0.0000  13.0810   5.3597  21.0573   6.2139  15.1663   7.5770  22.2870   
p2   13.0810   0.0000  15.8004  20.7696  11.5262  12.5880  12.2811  22.6390   
p3    5.3597  15.8004   0.0000  20.3048   8.5042  14.2484  11.5754  21.1658   
p4   21.0573  20.7696  20.3048   0.0000  20.7522  17.8183  24.9964  15.7370   
p5    6.2139  11.5262   8.5042  20.7522   0.0000  11.7827   6.4260  22.2764   
p6   15.1663  12.5880  14.2484  17.8183  11.7827   0.0000  17.6122  15.6682   
p7    7.5770  12.2811  11.5754  24.9964   6.4260  17.6122   0.0000  26.0663   
p8   22.2870  22.6390  21.1658  15.7370  22.2764  15.6682  26.0663   0.0000   
p9    5.8136  16.5451   7.8223  25.0834   9.0607  20.1520   6.5642  25.0077   
p10  17.2017  14.5420  16.0850  19.0948  14.0794   5.5793  19.5309  16.4835   
p11   7.0603  16.5630   9.6980  26.5480  10.2167  21.3835   4.6714  27.3081   
p12  16.2581  23.7088  15.7029  27.

## 2.

In [15]:
df = pd.read_csv('/content/kddcup.data.corrected', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,32,33,34,35,36,37,38,39,40,41
0,0,tcp,http,SF,215,45076,0,0,0,0,...,0,0.0,0.0,0.00,0.00,0.0,0.00,0.0,0.0,normal.
1,0,tcp,http,SF,162,4528,0,0,0,0,...,1,1.0,0.0,1.00,0.00,0.0,0.00,0.0,0.0,normal.
2,0,tcp,http,SF,236,1228,0,0,0,0,...,2,1.0,0.0,0.50,0.00,0.0,0.00,0.0,0.0,normal.
3,0,tcp,http,SF,233,2032,0,0,0,0,...,3,1.0,0.0,0.33,0.00,0.0,0.00,0.0,0.0,normal.
4,0,tcp,http,SF,239,486,0,0,0,0,...,4,1.0,0.0,0.25,0.00,0.0,0.00,0.0,0.0,normal.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4898426,0,tcp,http,SF,212,2288,0,0,0,0,...,255,1.0,0.0,0.33,0.05,0.0,0.01,0.0,0.0,normal.
4898427,0,tcp,http,SF,219,236,0,0,0,0,...,255,1.0,0.0,0.25,0.05,0.0,0.01,0.0,0.0,normal.
4898428,0,tcp,http,SF,218,3610,0,0,0,0,...,255,1.0,0.0,0.20,0.05,0.0,0.01,0.0,0.0,normal.
4898429,0,tcp,http,SF,219,1234,0,0,0,0,...,255,1.0,0.0,0.17,0.05,0.0,0.01,0.0,0.0,normal.


In [16]:
categorical_columns = df.select_dtypes(include=['object']).columns
print('categorical attributes:', categorical_columns)
categorical_data = df[categorical_columns]
print('categorical data:\n', categorical_data)

categorical attributes: Index([1, 2, 3, 41], dtype='int64')
categorical data:
           1     2   3        41
0        tcp  http  SF  normal.
1        tcp  http  SF  normal.
2        tcp  http  SF  normal.
3        tcp  http  SF  normal.
4        tcp  http  SF  normal.
...      ...   ...  ..      ...
4898426  tcp  http  SF  normal.
4898427  tcp  http  SF  normal.
4898428  tcp  http  SF  normal.
4898429  tcp  http  SF  normal.
4898430  tcp  http  SF  normal.

[4898431 rows x 4 columns]


In [17]:
#Kiem tra gia tri giong nhau
print('so luong dong giong nhau: ', categorical_data.duplicated().sum())

# Loai bo cac dong giong nhau
df1 = categorical_data.drop_duplicates()
print('Du lieu sau khi xoa nhung dong giong nhau: \n', df1)

so luong dong giong nhau:  4897822
Du lieu sau khi xoa nhung dong giong nhau: 
           1         2     3                 41
0        tcp      http    SF           normal.
1288     tcp      http    S2           normal.
1484     tcp      http    S1           normal.
2062     tcp      smtp    SF           normal.
2067     udp  domain_u    SF           normal.
...      ...       ...   ...               ...
4574130  tcp       bgp   REJ          neptune.
4575586  tcp    Z39_50   REJ          neptune.
4578870  tcp      smtp    SF          neptune.
4579297  tcp     other  RSTO          neptune.
4810949  tcp    telnet  RSTO  buffer_overflow.

[609 rows x 4 columns]


In [18]:
# Lấy 100 dòng
data = df1.iloc[:100, :].values
n = data.shape[0]
d = data.shape[1]

# Tính tần suất số lần xuất hiện
frequencies = {}
for col in range(d):
    value_counts = pd.Series(data[:, col]).value_counts()
    frequencies[col] = value_counts.to_dict()

def overlap_coefficient(x, y):
    sim = 0
    for i in range(len(x)):
        if x[i] == y[i]:
            sim += 1
    return sim / len(x)

def iof(x, y):
    sim = 0
    for i in range(len(x)):
        freq_x = frequencies[i].get(x[i], 1)
        freq_y = frequencies[i].get(y[i], 1)
        if x[i] == y[i]:
            sim += 1
        else:
            sim += 1 / (1 + np.log(freq_x) * np.log(freq_y))
    return sim / len(x)

# matrix
overlap_sim_matrix = np.zeros((n, n))
iof_sim_matrix = np.zeros((n, n))

for i in range(n):
    for j in range(i + 1, n):
        overlap_sim = overlap_coefficient(data[i], data[j])
        overlap_sim_matrix[i, j] = overlap_sim
        overlap_sim_matrix[j, i] = overlap_sim

        iof_sim = iof(data[i], data[j])
        iof_sim_matrix[i, j] = iof_sim
        iof_sim_matrix[j, i] = iof_sim

def find_nearest_neighbors(sim_matrix, k=5):
    nearest_neighbors = {}
    for i in range(n):
        sim_matrix[i, i] = -1
        indices = np.argsort(sim_matrix[i])[::-1]
        top_k_indices = indices[:k]
        top_k_similarities = sim_matrix[i, top_k_indices]
        nearest_neighbors[i] = list(zip(top_k_indices, top_k_similarities))
    return nearest_neighbors

k = 5
overlap_neighbors = find_nearest_neighbors(overlap_sim_matrix, k)
iof_neighbors = find_nearest_neighbors(iof_sim_matrix, k)

print("Overlap")
for i, neighbors in overlap_neighbors.items():
    print(f"Point {i}:")
    for neighbor, sim in neighbors:
        print(f"  - Point {neighbor}: {sim:.4f}")

print("IOF")
for i, neighbors in iof_neighbors.items():
    print(f"Point {i}:")
    for neighbor, sim in neighbors:
        print(f"  - Point {neighbor}: {sim:.4f}")

print("\nMatrix Overlap")
labels = [f"Point {i}" for i in range(n)]
df_overlap = pd.DataFrame(overlap_sim_matrix, index=labels, columns=labels)
print(df_overlap.iloc[:100, :100].round(4))

print("\nMatrix IOF")
df_iof = pd.DataFrame(iof_sim_matrix, index=labels, columns=labels)
print(df_iof.iloc[:100, :100].round(4))

Overlap
Point 0:
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 14: 0.7500
  - Point 2: 0.7500
  - Point 7: 0.7500
Point 1:
  - Point 0: 0.7500
  - Point 2: 0.7500
  - Point 14: 0.7500
  - Point 15: 0.7500
  - Point 24: 0.7500
Point 2:
  - Point 1: 0.7500
  - Point 10: 0.7500
  - Point 15: 0.7500
  - Point 32: 0.7500
  - Point 24: 0.7500
Point 3:
  - Point 96: 0.7500
  - Point 81: 0.7500
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 0: 0.7500
Point 4:
  - Point 12: 0.7500
  - Point 75: 0.5000
  - Point 27: 0.5000
  - Point 0: 0.5000
  - Point 11: 0.5000
Point 5:
  - Point 75: 0.7500
  - Point 6: 0.7500
  - Point 0: 0.7500
  - Point 11: 0.7500
  - Point 31: 0.7500
Point 6:
  - Point 75: 0.7500
  - Point 90: 0.7500
  - Point 0: 0.7500
  - Point 11: 0.7500
  - Point 31: 0.7500
Point 7:
  - Point 75: 0.7500
  - Point 11: 0.7500
  - Point 20: 0.7500
  - Point 10: 0.7500
  - Point 6: 0.7500
Point 8:
  - Point 17: 0.7500
  - Point 13: 0.7500
  - Point 75: 0.5000
  - Point 29: 0.500